#!/bin/bash
set -e

cd $(dirname $0)/..

mount --bind /host/dev /dev

source ./scripts/common

start_etcd
etcd_ip=$(get_container_ip $ETCD_SERVER)
wait_for_etcd $etcd_ip

export LONGHORN_ORC_TEST_ETCD_SERVER="$etcd_ip"
export LONGHORN_IMAGE="${LONGHORN_IMAGE}"

echo Running tests

PACKAGES="$(find . -name '*.go' | xargs -I{} dirname {} | sort -u | grep -Ev '(.git|.trash-cache|vendor|bin)')"

echo Packages: ${PACKAGES}

[ "${ARCH}" == "amd64" ] && RACE=-race
go test ${RACE} -cover -tags=test ${PACKAGES}
