#!/bin/bash
set -e

cd $(dirname $0)/..

if [ ! -x ./bin/latest_image ]; then
    ./scripts/package
fi

source ./scripts/common

image=`cat ./bin/latest_image`

mount --bind /host/dev /dev

start_etcd

etcd_ip=$(get_container_ip $ETCD_SERVER)
wait_for_etcd $etcd_ip

start_longhorn_binary rancher/longhorn:latest

image=`cat ./bin/latest_image`

orc1="${ORC_TEST_PREFIX}-server-1"
start_orc $image 1 ${etcd_ip}
orc1_ip=$(get_container_ip ${orc1})
wait_for_orc ${orc1_ip}

echo $orc1 is ready

export LONGHORN_ORC_TEST_SERVER_IPS="$orc1_ip"

cd integration
find -depth -name __pycache__ -o -name "*.pyc" -exec rm -rf {} \;
if [ -z "$NO_TEST" ]; then
    tox "$@"
fi
