#!/bin/bash
set -e

cd $(dirname $0)/..

if [ ! -x ./bin/latest_image ]; then
    ./scripts/package
fi

source ./scripts/common

image=`cat ./bin/latest_image`

# Removing any existing testing containers, e.g. from scripts/server
cleanup_orc_test

trap cleanup_orc_test EXIT

start_etcd

etcd_ip=$(get_container_ip $ETCD_SERVER)
wait_for_etcd $etcd_ip

start_nfs
nfs_ip=$(get_container_ip $NFS_SERVER)

start_longhorn_binary $LONGHORN_IMAGE

image=`cat ./bin/latest_image`

orc1="${ORC_TEST_PREFIX}-server-1"
start_orc $image 1 ${etcd_ip}
orc1_ip=$(get_container_ip ${orc1})
wait_for_orc ${orc1_ip}

echo $orc1 is ready

orc2="${ORC_TEST_PREFIX}-server-2"
start_orc $image 2 ${etcd_ip}
orc2_ip=$(get_container_ip ${orc2})
wait_for_orc ${orc2_ip}

echo $orc2 is ready

orc3="${ORC_TEST_PREFIX}-server-3"
start_orc $image 3 ${etcd_ip}
orc3_ip=$(get_container_ip ${orc3})
wait_for_orc ${orc3_ip}

echo $orc3 is ready

export LONGHORN_ORC_TEST_SERVER_IPS="$orc1_ip,$orc2_ip,$orc3_ip"
export LONGHORN_ORC_TEST_BACKUPSTORE_URL="nfs://${nfs_ip}:${BACKUPSTORE_PATH}"

cd integration
find -depth -name __pycache__ -o -name "*.pyc" -exec rm -rf {} \;
if [ -z "$NO_TEST" ]; then
    tox "$@"
fi
